name: Frontend Deploy to AWS S3
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nodejs Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{secrets.NODE_VERSION}}

      - name: Dependency installation
        run: npm install
        working-directory: src/frontend
        
      - name: App build
        run: npm run build
        working-directory: src/frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-north-1

      - name: Deploy to AWS S3
        run: aws s3 sync build s3://pl-dashboard-frontend-bucket --delete
        working-directory: src/frontend

        
